/***********************************************************************
*   Copyright (C) Huizhou Desay SV Automotive Co., Ltd.				   *
*				  All Rights Reserved.          					   *
*   Department : RN R&D SW1      									   *
*   AUTHOR	   : Shao Guangxian										   *
************************************************************************
* Object        : CAP.H
* Module        :
* Instance      :
* Description   :
*-----------------------------------------------------------------------
* Version:  0.1
* Date: 2011-11-24
* Author: Shao Guangxian
***********************************************************************/
/*-History--------------------------------------------------------------
* Version       Date    Name    Changes and comments
*
*=====================================================================*/
#ifndef _CAP_H_
#define _CAP_H_

/**** Definition of constants ****/


/**** Definition of types ****/


/**** Definition of macros ****/
#define CAP_ICSA_ICP1               0x80
#define CAP_ICSA_ICP0               0x40

/**** Declaration of constants ****/


/**** Declaration of variables ****/


/**** Declaration of functions ****/


#endif /*_CAP_H_*/
/**************** END OF FILE *****************************************/
