#ifndef   _DTIM_H_
#define   _DTIM_H_

#include "..\..\CONFIG\INC\CONFIG.H"
#include "..\..\CONFIG\INC\TYPES.H"
#include "DTIM_IF.H"

/**** Definition of constants ****/


/**** Definition of types ****/


/**** Definition of macros ****/


/**** Declaration of constants ****/


/**** Declaration of variables ****/


/**** Declaration of functions ****/


#endif /*_DTIM_H_*/
