/***********************************************************************
*   Copyright (C) Huizhou Desay SV Automotive Co., Ltd.				   *
*				  All Rights Reserved.          					   *
*   Department : RN R&D SW1      									   *
*   AUTHOR	   : Shao Guangxian										   *
************************************************************************
* Object        : FRT.H
* Module        :
* Instance      :
* Description   :
*-----------------------------------------------------------------------
* Version:  0.1
* Date: 2011-11-24
* Author: Shao Guangxian
***********************************************************************/
/*-History--------------------------------------------------------------
* Version       Date    Name    Changes and comments
*
*=====================================================================*/
#ifndef _FRT_H_
#define _FRT_H_

/**** Definition of constants ****/


/**** Definition of types ****/


/**** Definition of macros ****/
#define FRT_IRQZF        0x4000
#define FRT_ICLR         0x0200
#define FRT_BFE          0x0080
#define FRT_STOP         0x0040
#define FRT_UP_MODE      0x0000
#define FRT_UP_DOWN_MODE 0x0020
#define FRT_SCLR         0x0010
#define FRT_ICRE         0x0100

/**** Declaration of constants ****/


/**** Declaration of variables ****/


/**** Declaration of functions ****/

#endif /*_FRT_H_*/

/****************************** END OF FILE ***************************/

