/***********************************************************************
*   Copyright (C) Huizhou Desay SV Automotive Co., Ltd.				   *
*				  All Rights Reserved.          					   *
*   Department : RN R&D SW1      									   *
*   AUTHOR	   : Shao Guangxian										   *
************************************************************************
* Object        :
* Module        :
* Instance      :
* Description   :
*-----------------------------------------------------------------------
* Version:
* Date:
* Author:
***********************************************************************/
/*-History--------------------------------------------------------------
* Version       Date    Name    Changes and comments
*
*=====================================================================*/
#ifndef _GPIO_H_
#define _GPIO_H_
/**** Definition of constants ****/


/**** Definition of types ****/


/**** Definition of macros ****/


/**** Declaration of constants ****/
#define GPIO_PDIR_BASE  0x42666000/*define PDIR start Address*/
#define GPIO_PDOR_BASE  0x42668000/*define PDOR start Address*/
#define GPIO_DDR_BASE   0x42664000/*define DDR start Address*/

/**** Declaration of variables ****/


/**** Declaration of functions ****/


#endif
/****************************** END OF FILE ***************************/
